# Generated by Django 3.0.4 on 2020-10-25 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.detail


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='data di publish')),
                ('pub_date_end', models.DateTimeField(verbose_name='data ditutup')),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('w', 'withdrawn')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsView',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='voting.Question')),
            ],
            bases=(django.views.generic.detail.DetailView, 'voting.question'),
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_shot', models.ImageField(blank=True, upload_to='profil_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='calon pilihan')),
                ('choice_text2', models.CharField(default='', max_length=200, verbose_name='Wakil Calon Pilihan')),
                ('enkripsi', models.BinaryField(default=None)),
                ('enkripsi_stats', models.CharField(default='No', max_length=100)),
                ('votes', models.IntegerField(db_column='votes', default=0, verbose_name='jumlah')),
                ('image', models.ImageField(upload_to='post_image')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'user')},
            },
        ),
    ]
