# Generated by Django 3.0.4 on 2020-10-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20201026_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='head_shot',
            field=models.ImageField(upload_to='profil_images'),
        ),
    ]
