# Generated by Django 3.0.4 on 2020-10-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20201026_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='kunci_privat',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='kunci_publik',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
