# Generated by Django 3.0.4 on 2020-11-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20201027_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=35, verbose_name='calon pilihan'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text2',
            field=models.CharField(default='', max_length=35, verbose_name='Wakil Calon Pilihan'),
        ),
    ]
