# Generated by Django 3.0.4 on 2020-11-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20201105_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(max_length=1),
        ),
    ]
