# Generated by Django 3.0.4 on 2020-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20201127_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
