# Generated by Django 3.0.4 on 2020-11-27 17:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0013_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='users',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default=None, max_length=150, verbose_name=django.contrib.auth.models.User),
        ),
    ]
