# Generated by Django 3.0.4 on 2020-11-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20201128_0059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
