# Generated by Django 3.0.4 on 2020-11-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_auto_20201128_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanager',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usermanager',
            name='is_staff',
        ),
    ]
