# Generated by Django 3.0.4 on 2020-12-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_auto_20201128_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
