# Generated by Django 3.0.4 on 2021-02-05 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0019_auto_20201204_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemilih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_shot', models.ImageField(help_text='Gambar wajah yang digunakan untuk validasi masuk sistem pemungutan suara', upload_to='profil_images', verbose_name='Foto Wajah')),
                ('is_pemilih', models.BooleanField(default=False, help_text='Menentukan apakah pengguna merupakan kategori pemilih atau tidak', verbose_name='Pemilih')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pemilih',
                'verbose_name_plural': 'Pemilih',
            },
        ),
        migrations.RemoveField(
            model_name='foto',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Pilihan', 'verbose_name_plural': 'Pilihan'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pemungutan Suara', 'verbose_name_plural': 'Pemungutan Suara'},
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Judul Pemungutan Suara'),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
