# Generated by Django 3.0.4 on 2021-02-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0020_auto_20210205_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilih',
            name='head_shot_status_pass',
            field=models.BooleanField(default=False, help_text='Menentukan apakah pengguna dapat masuk tanpa validasi wajah', verbose_name='lewati validasi wajah'),
        ),
    ]
